

site_name: CIIED Website
theme:
  name: material
  markdown_extensions:
  - attr_list
  - md_in_html
  - offline
  - toc:
      permalink: true
      permalink_class: headerlink
      permalink_symbol: ¶

    plugins:
  - optimize 

  theme:
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


nav:
  - Home: index.md
  - About CIIED: about.md
  - Objectives: objectives.md
  - Activities: activities.md
  - Events: events.md
  - Contact: contact.md

  

