

site_name: CIIED Website
theme:
  name: material
  markdown_extensions:
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - About CIIED: about.md
  - Objectives: objectives.md
  - Activities: activities.md
  - Events: events.md
  - Contact: contact.md

  

